### ISSUE TITLE
Packaging issue - missing library

### ISSUE THREAD

**Issue by Patch86UK** [StarLabsLtd/coreboot-configurator#1]
On Ubuntu 20.04.3, on a newly delivered Lab Top Mk IV (so presumably fresh install).

Installed using command `sudo apt install coreboot-configurator`. Application installs successfully, icon is correctly added to launcher etc., however application won't open. Attempting to launch it via terminal returns error:
`coreboot-configurator: error while loading shared libraries: libyaml-cpp.so.0.6: cannot open shared object file: No such file or directory`

I manually installed `libyaml-cpp0.6` using apt, and it is now launching correctly.

Presumably it's a missing dependency on the deb.

**Comment by Sean-StarLabs** [comment]
Thank you :)
