### ISSUE TITLE
Not Appear Intel VT-d

### ISSUE THREAD

**Issue by ghost** [StarLabsLtd/coreboot-configurator#12]
Hello, 

my coreboot-configurator not appear Intel VT-d (My coreboot is the recent in a Thinkpad W500).

![photo_2022-04-03_12-04-06](https://user-images.githubusercontent.com/2234645/161434332-b0203e3e-e6de-4758-a795-6a52685a4469.jpg)

Why does it happen?

att

**Comment by Sean-StarLabs** [comment]
coreboot-configurator will find all the options available in coreboot. If it doesn't show an option, either there or in the Raw tab, it means that it doesn't exist in your coreboot build.

**Comment by Sean-StarLabs** [comment]
No response
