### ISSUE TITLE
Fedora 37 coreboot-configurator dependency on Fedora 38

### ISSUE THREAD

**Issue by ReprOTL** [StarLabsLtd/coreboot-configurator#24]
Attempting to install coreboot-configurator on Fedora 38 springs this error:
```
Error: 
 Problem: conflicting requests
  - nothing provides libyaml-cpp.so.0.6()(64bit) needed by coreboot-configurator-8-1.fc37.x86_64
(try to add '--skip-broken' to skip uninstallable packages)

```
This seems to be similar to a previous issue where libyaml-cpp0.6 was a required dependency, but this is also trying to use a dependency and install coreboot-configurator for an older version of Fedora.

**Comment by gala4444** [comment]
I have the same issue, I cannot use coreboot-configurator since upgraded to Fedora 38

**Comment by ReprOTL** [comment]
Issue seems to have been fixed with one of the commits a last week, I will close as solved as this is no longer an issue
