### ISSUE TITLE
`nvramtool: CMOS option table not found in coreboot table` with BIOS 8.6.0

### ISSUE THREAD

**Issue by djdembeck** [StarLabsLtd/coreboot-configurator#25]
After updating to BIOS v8.6.0 (EC v1.14) on a Starbook Mk V, `coreboot-configurator` no longer launches, with the error:
```
nvramtool: CMOS option table not found in coreboot table.  Apparently, the coreboot installed on this system was built without selecting CONFIG_USE_OPTION_TABLE.
```

I am on Ubuntu 22.04.

**Comment by billwanjohi** [comment]
If anyone else stumbles on this, I later found this related comment: https://github.com/StarLabsLtd/firmware/issues/117#issuecomment-1649422673

> You don't need it anymore, options are in the boot menu

Which suggests that this GUI is abandoned and you should remove it from your system once your BIOS is up to 8.60.

If anyone at Star Labs sees this, can you give any consideration at all to communicating to your customers? This (moving configuration to the boot menu) might be a great improvement to the status quo, but most of us experienced it as software breaking and not having any clue how to fix it.
