### ISSUE TITLE
yaml-cpp error when running coreboot-configurator 

### ISSUE THREAD

**Issue by 99mrm** [StarLabsLtd/coreboot-configurator#8]
Hello, 

I've managed to build coreboot-configurator but when running it I get this error:
`terminate called after throwing an instance of 'YAML::ParserException'
  what():  yaml-cpp: error at line 2, column 13: illegal map value
Aborted
`

I'm not sure how to fix this. In Ubuntu 21.10 everything works fine after installing it from the ppa. 
Still I would like to build it on some other distros. The new starbook is amazing so far! Any help is much appreciated

**Comment by cwebster2** [comment]
I am also seeing this error compiling on arch.

meson builld finds yaml-cpp

    Run-time dependency yaml-cpp found: YES 0.7.0

The binary is correctly linked against it

    libyaml-cpp.so.0.7 => /usr/lib/libyaml-cpp.so.0.7 (0x00007fd7289dd000)

And running the binary produces the same error as the OP

    ❯ coreboot-configurator
    terminate called after throwing an instance of 'YAML::ParserException'
      what():  yaml-cpp: error at line 2, column 13: illegal map value
    [1]    189691 abort (core dumped)  coreboot-configurator

This against commit d4bacd68933c37ca8e870836d968e623f56a4d20
